### ISSUE TITLE
Game does not start, cannot load Steamworks.NET.dll

### ISSUE THREAD

**Issue by Elektronixx** [Filigrani/SkyCoop#60]
**Mod Version:** LTS Release 11.6
**Game Version:** v2.16  
**MelonLoader Version:** v0.6.1
**Launcher:** Steam 
**Additional mods installed:** No 
**Perspective:** Host

### Description
The Game / Melonloader crashes when loading the Steamworks.NET.dll

### How to reproduce
1. Manually install MelonLoader 0.6.1
2. Extracting Skycooprelease into "Mods" Folder
3. Starting the Game

### Expected behavior
The Game starting

### Logs

**Host side log**
```
[22:13:06.904] ------------------------------
[22:13:06.931] MelonLoader v0.6.1 Open-Beta
[22:13:06.932] OS: Windows 11
[22:13:06.932] Hash Code: 696B58144EEC73C72FA36A811CA73312EEE4EC28AD5E3527BDA1E14F388A
[22:13:06.932] ------------------------------
[22:13:06.932] Game Type: Il2cpp
[22:13:06.932] Game Arch: x64
[22:13:06.932] ------------------------------
[22:13:06.933] Core::BasePath = G:\SteamLibrary\steamapps\common\TheLongDark
[22:13:06.933] Game::BasePath = G:\SteamLibrary\steamapps\common\TheLongDark
[22:13:06.933] Game::DataPath = G:\SteamLibrary\steamapps\common\TheLongDark\tld_Data
[22:13:06.933] Game::ApplicationPath = G:\SteamLibrary\steamapps\common\TheLongDark\tld.exe
[22:13:06.933] Runtime Type: net6
[22:13:07.002] ------------------------------
[22:13:07.002] Game Name: TheLongDark
[22:13:07.002] Game Developer: Hinterland
[22:13:07.004] Unity Version: 2021.3.16f1
[22:13:07.004] Game Version: 2.16
[22:13:07.004] ------------------------------

[22:13:07.506] Preferences Loaded!

[22:13:07.521] Loading Plugins from 'G:\SteamLibrary\steamapps\common\TheLongDark\Plugins'...
[22:13:07.522] ------------------------------
[22:13:07.528] Melon Assembly loaded: '.\Plugins\AudioCore.dll'
[22:13:07.528] SHA256 Hash: 'c1fa5fa19c6f06e3b1418f7f7d60ccae9dbf931d7d8046f33dd148dec1c24b7f'

[22:13:07.558] ------------------------------
[22:13:07.558] AudioCore v1.0.0
[22:13:07.558] by Digitalzombie
[22:13:07.559] Assembly: AudioCore.dll
[22:13:07.560] ------------------------------
[22:13:07.561] ------------------------------
[22:13:07.561] 1 Plugin loaded.
[22:13:07.567] [AudioCore] Audio preInitialization ...
[22:13:07.672] [AudioCore] System.NullReferenceException: Object reference not set to an instance of an object.
   at AssetsTools.NET.Extra.AssetHelper.FindAssetClassByID(ClassDatabaseFile cldb, UInt32 id)
   at AssetsTools.NET.Extra.AssetsManager.GetTemplateBaseField(AssetsFile file, AssetFileInfoEx info, Boolean forceFromCldb)
   at AssetsTools.NET.Extra.AssetsManager.GetTypeInstance(AssetsFile file, AssetFileInfoEx info, Boolean forceFromCldb)
   at AudioCore.Audio_Enabler_Main.LoadGlobalgamemanagers()
   at AudioCore.AudioCore_Main.OnPreInitialization()
   at MelonLoader.MelonEvent.<>c.<Invoke>b__1_0(LemonAction x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 174
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[22:13:07.953] [MelonStartScreen] Initializing...
[22:13:07.981] [MelonStartScreen] Using Start Screen Theme: "Default"
[22:13:08.719] Loading Il2CppAssemblyGenerator...
[22:13:08.727] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[22:13:08.903] [Il2CppAssemblyGenerator] RemoteAPI.DumperVersion = null
[22:13:08.903] [Il2CppAssemblyGenerator] RemoteAPI.ObfuscationRegex = null
[22:13:08.904] [Il2CppAssemblyGenerator] RemoteAPI.MappingURL = null
[22:13:08.904] [Il2CppAssemblyGenerator] RemoteAPI.MappingFileSHA512 = null
[22:13:08.911] [Il2CppAssemblyGenerator] Using Dumper Version: 2022.1.0-pre-release.10
[22:13:08.911] [Il2CppAssemblyGenerator] Using Il2CppInterop Version = 1.4.5
[22:13:08.911] [Il2CppAssemblyGenerator] Using Unity Dependencies Version = 2021.3.16
[22:13:08.912] [Il2CppAssemblyGenerator] Using Deobfuscation Regex = null
[22:13:08.913] [Il2CppAssemblyGenerator] Cpp2IL is up to date.
[22:13:08.913] [Il2CppAssemblyGenerator] UnityDependencies is up to date.
[22:13:08.914] [Il2CppAssemblyGenerator] Checking GameAssembly...
[22:13:09.054] [Il2CppAssemblyGenerator] Assembly is up to date. No Generation Needed.

[22:13:09.084] Loading Mods from 'G:\SteamLibrary\steamapps\common\TheLongDark\Mods'...
[22:13:09.085] ------------------------------
[22:13:09.101] Melon Assembly loaded: '.\Mods\SkyCoop.dll'
[22:13:09.101] SHA256 Hash: 'd711733957ea6d6e0a776f2b9ef83ece9b68688c1d7ad5ad7e911aabbc35a1e0'
[22:13:09.106] Melon Assembly loaded: '.\Mods\Steamworks.NET.dll'
[22:13:09.106] SHA256 Hash: 'a61778cbce992f1d3ab48577d8c6c1c43778727b6127cdfa8b97eccc353ce6ab'
```

**Comment by Kycko** [comment]
Current mod version works only with TLD 2.02 and Melon 0.5.7.
